name: trader_app
description: "Trader mobile application for supercycle."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.1.0
  url_launcher: ^6.3.2
  cached_network_image: ^3.4.1
  get_it: ^8.2.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  smooth_page_indicator: ^1.2.1
  loading_indicator: ^3.1.1
  flutter_rating_bar: ^4.0.1
  dropdown_button2: ^2.3.9
  email_validator: ^3.0.0
  dio: ^5.8.0+1
  path: ^1.9.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  wolt_modal_sheet: ^0.11.0
  permission_handler: ^12.0.1
  logger: ^2.6.1
  mime: ^2.0.0
  http_parser: ^4.1.2
  device_info_plus: ^11.3.0
  carousel_slider: ^5.1.1
  easy_image_viewer: ^1.5.1
  percent_indicator: ^4.2.5
  device_preview: ^1.2.0
  lottie: ^3.3.1
  intl: 0.20.2
  flutter_svg: ^2.2.0
  expandable_page_view: ^1.0.17
  fl_chart: ^0.71.0
  image_picker: ^1.1.2
  flutter_localizations:
    sdk: flutter
  pinput: ^5.0.1
  curved_navigation_bar: ^1.0.6
  font_awesome_flutter: ^10.10.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.2
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  animations: ^2.1.1
  intl_phone_field: ^3.2.0
  connectivity_plus: ^7.0.0
  flutter_local_notifications: ^20.0.0
  firebase_messaging: ^16.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: 2.4.13
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - lib/features/
    - lib/features/home/
    - lib/features/home/data/
    - lib/features/home/data/repos/
    - lib/features/home/data/models/
    - lib/features/home/data/managers/
    - lib/features/home/data/managers/home_cubit/
    - lib/features/home/data/managers/profile_cubit/
    - lib/features/home/data/managers/shipments_cubit/
    - lib/features/home/presentation/
    - lib/features/home/presentation/views/
    - lib/features/home/presentation/widgets/
    - lib/features/home/presentation/widgets/home_chart/
    - lib/features/home/presentation/widgets/home_header/
    - lib/features/home/presentation/widgets/notifications/
    - lib/features/home/presentation/widgets/types_section/
    - lib/features/splash/
    - lib/features/splash/views/
    - lib/features/sign_in/
    - lib/features/sign_in/data/
    - lib/features/sign_in/data/repos/
    - lib/features/sign_in/data/cubits/
    - lib/features/sign_in/data/cubits/sign-in-cubits/
    - lib/features/sign_in/data/models/
    - lib/features/sign_in/presentation/
    - lib/features/sign_in/presentation/views/
    - lib/features/sign_in/presentation/widgets/
    - lib/features/sign_up/
    - lib/features/sign_up/data/
    - lib/features/sign_up/data/repos/
    - lib/features/sign_up/data/models/
    - lib/features/sign_up/data/managers/
    - lib/features/sign_up/data/managers/sign_up_cubit/
    - lib/features/sign_up/presentation/
    - lib/features/sign_up/presentation/views/
    - lib/features/sign_up/presentation/widgets/
    - lib/features/calculator/
    - lib/features/calculator/presentation/
    - lib/features/calculator/presentation/view/
    - lib/features/calculator/presentation/widget/
    - lib/features/contact_us/
    - lib/features/contact_us/data/
    - lib/features/contact_us/data/models/
    - lib/features/contact_us/presentation/
    - lib/features/contact_us/presentation/view/
    - lib/features/contact_us/presentation/widget/
    - lib/features/contact_us/presentation/controllers/
    - lib/features/onboarding/
    - lib/features/onboarding/presentation/
    - lib/features/onboarding/presentation/views/
    - lib/features/onboarding/presentation/widgets/
    - lib/features/environment/
    - lib/features/environment/data/
    - lib/features/environment/data/repos/
    - lib/features/environment/data/cubits/
    - lib/features/environment/data/cubits/eco_cubit/
    - lib/features/environment/data/cubits/requests_cubit/
    - lib/features/environment/data/cubits/create_request_cubit/
    - lib/features/environment/data/models/
    - lib/features/environment/presentation/
    - lib/features/environment/presentation/views/
    - lib/features/environment/presentation/widgets/
    - lib/features/environment/presentation/widgets/trees_tab/
    - lib/features/environment/presentation/widgets/impact_tab/
    - lib/features/environment/presentation/widgets/requests_tab/
    - lib/features/environment/presentation/widgets/achievements_tab/
    - lib/features/environment/presentation/widgets/transactions_tab/
    - lib/features/sales_process/
    - lib/features/sales_process/data/
    - lib/features/sales_process/data/cubits/
    - lib/features/sales_process/data/cubits/create_shipment_cubit/
    - lib/features/sales_process/data/repos/
    - lib/features/sales_process/data/models/
    - lib/features/sales_process/presentation/
    - lib/features/sales_process/presentation/views/
    - lib/features/sales_process/presentation/widgets/
    - lib/features/sales_process/presentation/widgets/steps/
    - lib/features/shipment_edit/
    - lib/features/shipment_edit/data/
    - lib/features/shipment_edit/data/repos/
    - lib/features/shipment_edit/data/cubits/
    - lib/features/shipment_edit/data/models/
    - lib/features/shipment_edit/presentation/
    - lib/features/shipment_edit/presentation/views/
    - lib/features/shipment_edit/presentation/widgets/
    - lib/features/forget_password/
    - lib/features/forget_password/data/
    - lib/features/forget_password/data/model/
    - lib/features/forget_password/data/repos/
    - lib/features/forget_password/data/cubits/
    - lib/features/forget_password/presentation/
    - lib/features/forget_password/presentation/views/
    - lib/features/forget_password/presentation/widgets/
    - lib/features/shipments_calendar/
    - lib/features/shipments_calendar/data/
    - lib/features/shipments_calendar/data/repos/
    - lib/features/shipments_calendar/data/cubits/
    - lib/features/shipments_calendar/data/cubits/shipments_calendar_cubit/
    - lib/features/shipments_calendar/data/models/
    - lib/features/shipments_calendar/presentation/
    - lib/features/shipments_calendar/presentation/view/
    - lib/features/shipments_calendar/presentation/widget/
    - lib/features/trader_main_profile/
    - lib/features/trader_main_profile/data/
    - lib/features/trader_main_profile/presentation/
    - lib/features/trader_main_profile/presentation/view/
    - lib/features/trader_main_profile/presentation/widgets/
    - lib/features/trader_main_profile/presentation/widgets/trader_profile_header/
    - lib/features/trader_main_profile/presentation/widgets/trader_branchs_section/
    - lib/features/trader_shipment_details/
    - lib/features/trader_shipment_details/data/
    - lib/features/trader_shipment_details/data/repos/
    - lib/features/trader_shipment_details/data/cubits/
    - lib/features/trader_shipment_details/data/cubits/shipment_cubit/
    - lib/features/trader_shipment_details/data/models/
    - lib/features/trader_shipment_details/presentation/
    - lib/features/trader_shipment_details/presentation/views/
    - lib/features/trader_shipment_details/presentation/widgets/
    - lib/features/notifications/
    - lib/features/notifications/data/
    - lib/features/notifications/presentation/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "#3BC577"  # لون الخلفية
  image_path: "assets/icons/trader_launcher.png"
