// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLmErHGGSMUMrSpzATrChQWZRe5aAQ4m8',
    appId: '1:483137593963:android:e6a12f5610195863a6472e',
    messagingSenderId: '483137593963',
    projectId: 'supercycle-trader',
    storageBucket: 'supercycle-trader.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO5nzXSGbQlb4pR_eTVcO22Dl_6accrJQ',
    appId: '1:483137593963:ios:6feca8b851343ca0a6472e',
    messagingSenderId: '483137593963',
    projectId: 'supercycle-trader',
    storageBucket: 'supercycle-trader.firebasestorage.app',
    androidClientId: '483137593963-otk3ovseeivqcs38i9nojk1s4ljsn3ba.apps.googleusercontent.com',
    iosClientId: '483137593963-k3jua98runf5m367ulv7pk29dkjhbbfa.apps.googleusercontent.com',
    iosBundleId: 'com.supercycle.trader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5V63HzMuZSizeKPnpLbWUOnSkNhCWsfA',
    appId: '1:855015056699:web:250f27484e8cae98d5831e',
    messagingSenderId: '855015056699',
    projectId: 'trader_app-b07f1',
    authDomain: 'trader_app-b07f1.firebaseapp.com',
    storageBucket: 'trader_app-b07f1.firebasestorage.app',
  );
}